import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

s1 = pd.read_csv('dc1.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s2 = pd.read_csv('dc2.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s3 = pd.read_csv('dc3.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s4 = pd.read_csv('dc4.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s5 = pd.read_csv('dc5.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s6 = pd.read_csv('dc6.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s7 = pd.read_csv('dc7.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s8 = pd.read_csv('dc8.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s9 = pd.read_csv('dc9.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s10 = pd.read_csv('dc10.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s11 = pd.read_csv('dc11.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s12 = pd.read_csv('dc12.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s13 = pd.read_csv('dc13.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s14 = pd.read_csv('dc14.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s15 = pd.read_csv('dc15.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s16 = pd.read_csv('scroll1.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s17 = pd.read_csv('scroll2.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s18 = pd.read_csv('scroll3.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s19 = pd.read_csv('scroll4.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])
s20 = pd.read_csv('scroll5.csv',names=['timestamp','acc_x','acc_y','acc_z','orientation'])

s1 = np.array(s1)
s2 = np.array(s2)
s3 = np.array(s3)
s4 = np.array(s4)
s5 = np.array(s5)
s6 = np.array(s6)
s7 = np.array(s7)
s8 = np.array(s8)
s9 = np.array(s9)
s10 = np.array(s10)
s11 = np.array(s11)
s12 = np.array(s12)
s13 = np.array(s13)
s14 = np.array(s14)
s15 = np.array(s15)
s16 = np.array(s16)
s17 = np.array(s17)
s18 = np.array(s18)
s19 = np.array(s19)
s20 = np.array(s20)

plt.xlabel('time (min)')
plt.ylabel("acc_x scroll (m/s^2)")
plt.ylim([-10,20])
plt.plot(s1[:][1])
plt.plot(s2[:][1])
plt.plot(s3[:][1])
plt.plot(s4[:][1])
plt.plot(s5[:][1])
plt.plot(s6[:][1])
plt.plot(s7[:][1])
plt.plot(s8[:][1])
plt.plot(s9[:][1])
plt.plot(s10[:][1])
plt.plot(s11[:][1])
plt.plot(s12[:][1])
plt.plot(s13[:][1])
plt.plot(s14[:][1])
plt.plot(s15[:][1])
plt.plot(s16[:][1])
plt.plot(s17[:][1])
plt.plot(s18[:][1])
plt.plot(s19[:][1])
plt.plot(s20[:][1])
plt.title('X-Axis Scroll Application Over 20 Sequences')
plt.show()

plt.xlabel('time (min)')
plt.ylabel("acc_x scroll (m/s^2)")
plt.ylim([-10,20])
plt.plot(s1[:][2])
plt.plot(s2[:][2])
plt.plot(s3[:][2])
plt.plot(s4[:][2])
plt.plot(s5[:][2])
plt.plot(s6[:][2])
plt.plot(s7[:][2])
plt.plot(s8[:][2])
plt.plot(s9[:][2])
plt.plot(s10[:][2])
plt.plot(s11[:][2])
plt.plot(s12[:][2])
plt.plot(s13[:][2])
plt.plot(s14[:][2])
plt.plot(s15[:][2])
plt.plot(s16[:][2])
plt.plot(s17[:][2])
plt.plot(s18[:][2])
plt.plot(s19[:][2])
plt.plot(s20[:][2])
plt.title('Y-Axis Scroll Application Over 20 Sequences')
plt.show()

plt.xlabel('time (min)')
plt.ylabel("acc_x scroll (m/s^2)")
plt.ylim([-10,20])
plt.plot(s1[:][3])
plt.plot(s2[:][3])
plt.plot(s3[:][3])
plt.plot(s4[:][3])
plt.plot(s5[:][3])
plt.plot(s6[:][3])
plt.plot(s7[:][3])
plt.plot(s8[:][3])
plt.plot(s9[:][3])
plt.plot(s10[:][3])
plt.plot(s11[:][3])
plt.plot(s12[:][3])
plt.plot(s13[:][3])
plt.plot(s14[:][3])
plt.plot(s15[:][3])
plt.plot(s16[:][3])
plt.plot(s17[:][3])
plt.plot(s18[:][3])
plt.plot(s19[:][3])
plt.plot(s20[:][3])
plt.title('Z-Axis Scroll Application Over 20 Sequences')
plt.show()